[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#3a5a8c"
backgroundColor = "#dce0e8"
secondaryBackgroundColor = "#cdd2dc"
textColor = "#1e2433"
font = "sans-serif"
baseFontSize = 17
